### ISSUE TITLE
Unthemed scrollbars appear on hover

### ISSUE THREAD

**Issue by SnoFox** [sn-extensions/folders-component#10]
Two minor issues:

1. A horizontal scrollbar keeps appearing on mouse-over of the Folder list. This happens regardless of how large I make the treebar.
2. The vertical scrollbar isn't themed like the other scrollbar components in Standard Note
Bonus: The horizontal scrollbar causes a vertical one to spawn if your window is too small.

I can provide some video if you want, just gotta create some test data for you...

**Comment by atmoio** [comment]
These are to be expected on Windows I'm afraid. Windows handles scrollbars really poorly, and makes it very difficult to work with. This is the best solution I've been able to find (to hide until hover).

For styling, extensions don't have themed scrollbars yet. Will possibly gain this in the future.

**Comment by bryvin** [comment]
Late reply, but this is now fixed and extensions are mostly (if not all) updated to utilize the same style for scrollbars.

**Comment by atmoio** [comment]
Yup 👍
