### ISSUE TITLE
Show "Archived"

### ISSUE THREAD

**Issue by fahrradflucht** [sn-extensions/folders-component#12]
When I use the folders extension there is no way to access archived notes anymore. I have to disable the extension to get to them. Or do I miss something here?

**Comment by atmoio** [comment]
You can use this [smart tag](https://standardnotes.org/help/42/how-do-i-view-a-list-of-untagged-notes) syntax for archived notes: `!["Archived", "archived", "=", true]`.

**Comment by fahrradflucht** [comment]
Works, thx!
