### ISSUE TITLE
Folder Extension Parent Problem

### ISSUE THREAD

**Issue by ghost** [sn-extensions/folders-component#13]
If you create a tag w/o folder extension enabled like i.love.sn. Then switch to folder extension. The only tag you see is sn. Perhaps it should automatically create i.love and i?

**Comment by atmoio** [comment]
Hmm...maybe. But if someone is using dot syntax without folders, can we assume that was their intention? Maybe they just wanted dots in their tag name..

**Comment by ghost** [comment]
On Mon, 2018-08-13 at 07:14 -0700, Mo Bitar wrote:
> Hmm...maybe. But if someone is using dot syntax without folders, can
> we assume that was their intention? Maybe they just wanted dots in
> their tag name..
> 
You're right. No way to tell. I've myself have gotten into the habit of
using the . as a way to dictate folders. However, there isn't a way to
absolutely know what the user wants unless we ask them ever time...That
would introduce user fatigue and SN is supposed to be simpe.  In the
name of keeping things simple and functional for the next 100 years.
I'll close and mark as solve.
