### ISSUE TITLE
Finding untagged items

### ISSUE THREAD

**Issue by elijahbrost** [sn-extensions/folders-component#25]
There should be a way to view *only* untagged items (ie. a tag that is applied automatically to all untagged items, and removed automatically from any item which other tags are added to). When you have thousands of notes, finding notes which are untagged, in order to tag them is a real task otherwise.

Wasn't sure if this issue would be better to bring up here, in repository of the Folders extension, or in the repository for the Web App itself.

**Comment by atmoio** [comment]
Please see here: https://standardnotes.org/help/42/how-do-i-view-a-list-of-untagged-notes-and-create-other-dynamic-filters
