### ISSUE TITLE
Folders extension - no folders / views displayed anymore

### ISSUE THREAD

**Issue by agba55** [sn-extensions/folders-component#31]
Somehow the folders extension is no longer displaying any folders / tags / nested tags. It's a complete blank space (see screenshot).

![hmmm](https://user-images.githubusercontent.com/47297127/52183152-4808e200-2805-11e9-90c5-a2f426028a61.JPG)

Here's what happened:
I had the folders extension installed and activated
Been playing around with views + smart tags
I started to rename the 'standard' view "all notes" "trash" and "archived" to "1 all notes", "3 Archived" and "4 Trash" to do some ordering of the existing views. 
I saw that there was a second set of All notes Trash Archived re-appearing (above the 1 All notes, 3 Archived etc). 
After refreshing , the side bar with tags is empty.

Deactivating the folders extensions causes the side bar to re-appear. I also see the tags i re-named, plus the ones you'd see by default (i.e. 2 sets of the same tags). However, i can no longer delete the tags i renamed.
![hmmm2](https://user-images.githubusercontent.com/47297127/52183216-180e0e80-2806-11e9-96a7-848a32b21976.JPG)

**Comment by karan** [comment]
Thanks for trying. I'm using brave latest.
