### ISSUE TITLE
Folders overlap with Trash

### ISSUE THREAD

**Issue by lokesh-krishna** [sn-extensions/folders-component#4]
When there are a large number of folders, the list overlaps the Trash. This makes it difficult to select folders and also makes it difficult to move folders into the Trash.

![trash_overlap](https://user-images.githubusercontent.com/20235646/28977012-e0ee9d3c-795d-11e7-841e-7b0aff906e04.png)

Here, the `Friends` folder is overlapping with the Trash.

**Comment by atmoio** [comment]
Hmm that's no good. Will take a look.

**Comment by atmoio** [comment]
This issue has been fixed, thanks.

**Comment by lokesh-krishna** [comment]
I updated to 1.2.5 to check how things are now and I don't think the issue has been fixed completely.
Things looked unchanged when I first opened the app:

![screenshot from 2017-08-23 08-25-27](https://user-images.githubusercontent.com/20235646/29596869-ba0510a2-87ae-11e7-9cab-ab2d83716dcb.png)

Except the Trash now appears to be highlighted which only highlights the problem.

Scrolling down however moves the trash down as well and reaching the end of the list moves the trash completely out of the list.

![screenshot from 2017-08-23 08-25-46](https://user-images.githubusercontent.com/20235646/29596895-e20ffc7e-87ae-11e7-88b9-f21021f0c58c.png)

Is there anyway you could make sure that Trash always stays at the bottom of the list?

**Comment by atmoio** [comment]
Well in this case this is the expected behavior. The trash overlaps everything but is fixed to the bottom. This allows you to to drag and drop. If it were hidden from view, the drag and drop wouldn't work as it would take custom code to move the scroll bar along with your mouse position, which would create too much unnecessary complexity. Perhaps a better solution is getting rid of the drag and drop all together and coming up with another way to delete tags here.

**Comment by lokesh-krishna** [comment]
Thanks for explaining :)

**Comment by OriginalFannibal** [comment]
Checked out Simplenote just to see how it handled deleting tags and found their solution quite elegant. Would like to hear what you think about it.

![screenshot from 2017-08-24 07-15-25](https://user-images.githubusercontent.com/20235646/29645665-8add4ef0-886e-11e7-91a4-56631287a144.png)

Opening the tags list shows all tags and next to them is the number of notes with that tag (which is a request for Standard Notes IIRC). That's the number next to "All Notes" in my screenshot. Hover over any tag and the number is replaced by a trashcan, clicking which asks for confirmation to delete the tag.

Using the Folders component, hovering over a tag gives you the option to create a nested folder and I appreciate that feature a lot. Putting a delete button anywhere near it would be disastrous. Standard Notes could show the number of notes with the tag next to the tag until you hover it though? I am just curious about what you think of their way of doing it.

**Comment by lokesh-krishna** [comment]
Checked out Simplenote just to see how it handled deleting tags and found their solution quite elegant. Would like to hear what you think about it.

![screenshot from 2017-08-24 07-15-25](https://user-images.githubusercontent.com/20235646/29645955-f2a4ecb8-886f-11e7-9e0f-1c142217073b.png)

Opening the tags list shows all tags and next to them is the number of notes with that tag (which is a request for Standard Notes IIRC). That's the number next to "All Notes" in my screenshot. Hover over any tag and the number is replaced by a trashcan, clicking which asks for confirmation to delete the tag.

Using the Folders component, hovering over a tag gives you the option to create a nested folder and I appreciate that feature a lot. Putting a delete button anywhere near it would be disastrous. Standard Notes could show the number of notes with the tag next to the tag until you hover it though? I am just curious about what you think of their way of doing it.

**Comment by atmoio** [comment]
That's a little trickier for the folders component since tags can be infinitely nested, and thus indented off screen, making hover links very difficult to use.
