### ISSUE TITLE
Tags are getting duplicated on each application start

### ISSUE THREAD

**Issue by shockinghobby** [sn-extensions/folders-component#41]
There seems to be an issue after the 1.3.4 update. Default views (All notes, Archived, Trash) are getting duplicated as tags upon each application start.

Disabling Folders extension fixes this behavior. Extra tags can be deleted. But re-enabling the extension first creates three tags and then starts duplicating them on each launch.

Edit: Platform is ArchLinux, using AppImage.

**Comment by atmoio** [comment]
(Dev note here for future reference: https://github.com/standardnotes/folders-component/blob/master/Todo.md)
