### ISSUE TITLE
How to build custom filters

### ISSUE THREAD

**Issue by ghost** [sn-extensions/folders-component#46]
Hi all,

In the readme it says "Folders also supports Smart Tags, which allow you to build custom filters for viewing your notes"
If I press the plus button next to Views and start tipping I get a new tag not a custom view.

So my question is, how can I get those custom views?

Thanks in advance

**Comment by tab0r** [comment]
Not a dev, but I found a help article that got me where I needed to go:

https://standardnotes.org/help/42/how-do-i-view-a-list-of-untagged-notes-and-create-other-dynamic-filters

I copied most of the examples into a note, as well as creating them. Just to be sure I have a reference there.

**Comment by ghost** [comment]
Thanks that works even though the syntax is not that easy ;)

**Comment by JaspalSuri** [comment]
>Thanks that works even though the syntax is not that easy ;)

If you need any help with setting up specific filters, we'd be happy to assist!

**Comment by jmason888** [comment]
After the tags-folders migration, I do I refer to child folders in the (newly renamed) Smart Filters?
