### ISSUE TITLE
don't display the add button for "Views" 

### ISSUE THREAD

**Issue by chaserene** [sn-extensions/folders-component#58]
if you select the "Views" parent item and hover over it with the mouse, the label addition button appears. if you click it, it even creates a child label, but after finishing naming, the label becomes a child of "All". this is already possible to do with "All" so I think this should be made impossible for consistency reasons.

**Comment by JaspalSuri** [comment]
Hi @chaserene, this option exists for [Dynamic Filters / Smart Tags](https://standardnotes.org/help/42/how-do-i-view-a-list-of-untagged-notes-and-create-other-dynamic-filters); when a normal tag is added, it ends up in the normal tags list under _**All**_. 🙂

**Comment by chaserene** [comment]
my bad, I was unaware of this use case. it's actually amazing!

**Comment by JaspalSuri** [comment]
No worries; glad to hear that!
