### ISSUE TITLE
Feature request: Ability to be able to collapse / Expand the Folders/Tags.subtags

### ISSUE THREAD

**Issue by kalivas** [sn-extensions/folders-component#9]
Hello, team, it would be really helpful for the folders component to be able to expand and collapse the nested tags. 

On other systems with similar features under each tag, I usually add dozens of subtags, therefore having them all expanded, I only see 1 top item and the rest get lost way down.

Do you have plans for implementing such a feature on the folders component extension?

Thanks!

**Comment by atmoio** [comment]
No plans yet but will keep this in mind..

**Comment by kalivas** [comment]
Alright, thanks for the input.

**Comment by jedypod** [comment]
I would love to see this feature. It can get very visually cluttered with many nested subfolders, and it would be very useful to be able to collapse or expand a folder hierarchy.

**Comment by LudwikJaniuk** [comment]
This exists now

**Comment by atmoio** [comment]
Yup, press the circle next to folder name to toggle expand/collapse.

**Comment by kalivas** [comment]
@mobitar Some amazing additions to the software the past year, this added (thanks! :D), spreadsheets!!!! Man... Standard Notes are going places...keep up the good work.

**Comment by atmoio** [comment]
Haha thanks @kalivas, glad to hear you're a fan of the progress!
